### ISSUE TITLE
DC cannot connect to Internet

### ISSUE THREAD

**Issue by cengxiye** [DellGEOS/AzureStackHOLs#19]
I followed with the below 2 articles first
[01 How to Hydrate MSLab files]
[02 Working with MSLab]
After deploying all VM in [02 Working with MSLab], the DC is not able to access the Internet.

Then I cleaned the VMs deployed in [02 Working with MSLab], and tried [01 Deploy Azure Stack HCI Cluster with Windows Admin Center], DC is now able to access the Internet.

Thanks.

**Comment by jaromirk** [comment]
Hello, yep, DC will be connected in this step to explain parameter Internet=$true :). Does it make sense? https://github.com/DellGEOS/AzureStackHOLs/tree/main/admin-guides/02-WorkingWithMSLab#connecting-lab-to-internet
