### ISSUE TITLE
Failed to import a virtual machine

### ISSUE THREAD

**Issue by synGlo** [DellGEOS/AzureStackHOLs#24]
Hi, 
Can someone help me?
I have hydrated the labs fine but when I try to deploy (the first step in https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/01-DeployAzureStackHCICluster-WAC) I receive this error:

```
Import-VM : Failed to import a virtual machine.
An unexpected error occurred: The source type for URI '%1' is not supported. (0xC00CEF0B).
Failed to import a virtual machine.
The Hyper-V Virtual Machine Management service encountered an unexpected error: The source type for URI '%1' is not 
supported. (0xC00CEF0B).
```

Here's the log.

**********************
Windows PowerShell transcript start
Start time: 20221028142831
Username: WIN-GGD0IQMTGDG\Administrator
RunAs User: WIN-GGD0IQMTGDG\Administrator
Machine: WIN-GGD0IQMTGDG (Microsoft Windows NT 10.0.14393.0)
Host Application: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command if((Get-ExecutionPolicy ) -ne 'AllSigned') { Set-ExecutionPolicy -Scope Process Bypass }; & 'C:\Lab\Deploy.ps1'
Process ID: 4532
PSVersion: 5.1.14393.3866
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14393.3866
BuildVersion: 10.0.14393.3866
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Lab\Deploy.log
Script started at 10/28/2022 14:28:31

MSLab Version v22.10.1

Lab telemetry
By providing a telemetry information you will help us to improve MSLab scripts. There are two levels of a telemetry information and we are not collecting any personally identifiable information (PII).
Details about telemetry levels and the content of telemetry messages can be found in documentation https://aka.ms/mslab/telemetry
Available telemetry levels are:
 * None  -- No information will be sent
 * Basic -- Information about lab will be sent (e.g. script execution time, number of VMs, guest OSes)
 * Full  -- Information about lab and the host machine (e.g. type of disk)
Would you be OK with providing an information about your MSLab usage?

Tip: You can also configure telemetry settings explicitly in LabConfig.ps1 file or by setting an environmental variable and suppress this prompt.

No telemetry information will be sent.
List of variables used
	 Prefix used in lab is Lab-
	 Switchname is Lab-LabSwitch
	 Workdir is C:\Lab
	 LabFolder is C:\Lab\LAB
Checking if OS is Windows 10 1511 (10586)/Server 2016 or newer
	 OS is Windows 10 1511 (10586)/Server 2016 or newer
Checking if Hyper-V is installed
	 Hyper-V is Installed
Checking if Hyper-V Powershell module is installed
	 Hyper-V is Installed
Checking if at least 2GB RAM is available
	 13,729 MB RAM Available
Checking if volume filesystem is NTFS or ReFS
	 Volume filesystem is NTFS
Creating Switch
	 Checking if Lab-LabSwitch already exists...
	 Creating Lab-LabSwitch...

Internet connectivity requested
	 Detecting default vSwitch
	 Default switch not present, detecting external vSwitch Lab-LabSwitch-External
	 Detecting external VMSwitch
	 External vswitch vmxnet3 Ethernet Adapter - Virtual Switch found. Will be used for connecting lab to internet
Checking if lab already exists.
	 Starting IP for AdditionalNetworks is 1
Creating Mountdir
Creating VMs dir
Looking for Tools Parent Disks
	 Tools parent disk C:\Lab\ParentDisks\tools.vhdx found
Configuring DC
	 Looking for DC to be imported
Import-VM : Failed to import a virtual machine.

An unexpected error occurred: The source type for URI '%1' is not supported. (0xC00CEF0B).

Failed to import a virtual machine.

The Hyper-V Virtual Machine Management service encountered an unexpected error: The source type for URI '%1' is not 
supported. (0xC00CEF0B).
At C:\Lab\Deploy.ps1:1604 char:27
+                     $DC = Import-VM -Path $_.FullName
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.ImportVM
DC was not imported successfully Press any key to continue ...
Press enter to continue ...
**********************
Windows PowerShell transcript end
End time: 20221028142843
**********************

**Comment by jaromirk** [comment]
ca you check what is in your folder  C:\Lab\LAB\DC ? There should be Virtual Hard Disks folder where DC.vhdx should be residing. I suspect something went wrong during 2_createparentdisks.ps1 phase? 
![image](https://user-images.githubusercontent.com/9829838/207820351-acd2b36d-52a5-427d-8667-1e20a9973b8d.png)

**Comment by jaromirk** [comment]
oh snap, you opened issue in October. you can also reach me out at jaromir.kaspar@dell.com - i completely missed this.

**Comment by Karl-WE** [comment]
@jaromirk can this one be closed? It is very old. not seeing this issue in mslab 24.01.
