### ISSUE TITLE
07-ExpandingAzureStackHCICluster does not reflect 22H2 changes

### ISSUE THREAD

**Issue by jaromirk** [DellGEOS/AzureStackHOLs#38]
Converting volumes instead of recreating volumes should be added.

https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/07-ExpandingAzureStackHCICluster

**Comment by Karl-WE** [comment]
@jaromirk link appears to be dead.
Scenario is marked deprecated by yourself
https://github.com/DellGEOS/AzureStackHOLs/tree/main/deprecated/ExpandingAzureStackHCICluster

appears this can be closed as you added a remark in regards here
https://github.com/DellGEOS/AzureStackHOLs/tree/main/deprecated/ExpandingAzureStackHCICluster#about-the-lab
