### ISSUE TITLE
Network HUD might not be deployed correctly

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#43]
Dear @jaromirk  I tried to deploy network HUD, yet it does not setup correctly (eventually not anymore).

related:
https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/02a-DeployAzureStackHCICluster22H2-PowerShell-NetATC#task-12---configure-network-hud

This issue might appear:
https://techcommunity.microsoft.com/t5/networking-blog/network-hud-november-2022-content-update-has-arrived/bc-p/3877426/highlight/true#M566

**Comment by jaromirk** [comment]
Last time I tried it was last week and it deployed correctly. Do you have some error output?

**Comment by Karl-WE** [comment]
Hi there, it wasn't reproducible. Next time I will catch the error message in a snip. Thanks for your time!
