### ISSUE TITLE
Set Livemigration settings on cluster level

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#44]
Dear @jaromirk some parts of your code uses a per node configuration for LiveMigration. Good news this can now be done cluster-wide, the changes become effective quite immediately.

https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/02a-DeployAzureStackHCICluster22H2-PowerShell-NetATC#task-10---configure-cluster-aware-updating

this is valid for WS 2022 and Azure Stack HCI:
https://techcommunity.microsoft.com/t5/azure-stack/azure-stack-hci-keeps-setting-livemigration-to-1-here-is-why/td-p/3850965

**Comment by jaromirk** [comment]
Yeah, but this guide does it using NetATC global overrides.

**Comment by jaromirk** [comment]
Task 14, step 2

https://github.com/DellGEOS/AzureStackHOLs/tree/main/lab-guides/02a-DeployAzureStackHCICluster22H2-PowerShell-NetATC#task-14---adjust-netatc-global-overrides

**Comment by Karl-WE** [comment]
Since I understand you do not likely have the time to update older scenarios, I am not looking to waste your time and closing this PR.
