### ISSUE TITLE
new labconfig variables for Microsoft Telemetry and TimeZone

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#51]
hi Jaromir in addition to #50 I would like to add two default switches into the mslab config which represent the timezone used in the lab,  UTC might not be feasible for some,

aswell as specifying the OS telemetry level. even though it is a lab Microsoft can still benefit from optional telemetry as many corporations leave it at default or turn it of or worse (blocking by DNS, URL).

If you appreciate the idea I can share you my deployment code for the Deploy.ps1 so you don't have to do this.

**Comment by jaromirk** [comment]
Telemetry option is already there
https://github.com/microsoft/MSLab/blob/master/Scripts/LabConfig.ps1#L41

Timezone can be set with custom powershell command
https://github.com/microsoft/MSLab/blob/master/Scripts/LabConfig.ps1#L341-L343

**Comment by Karl-WE** [comment]
Well missed the first option I thought it is the MS lab telemetry.
For the TZ as you recently changed the default it would be cool to have an option instead of a custom command, don't you think?
So we could use the Timezone ID as parameter.
