### ISSUE TITLE
using PSWindowsUpdate Module instead current patching

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#52]
I understand we want to keep 3rd party components near zero but in this case I propose that using PSWindowsUpdate should be very feasible, reduce code and improve readability. I am using this for customers in production when they are not looking into Azure Update Manager (yet)

references:
https://woshub.com/pswindowsupdate-module/
https://www.virtualizationhowto.com/2023/06/pswindowsupdate-automated-windows-updates-with-powershell/

if you appreciate the Idea, I can share you the code I use for my 22H2, which could fairly be used for any deployment version.

**Comment by jaromirk** [comment]
Does not work all the time and it's using compiled dll, that might not work for everyone. And it will not work with code signing. 
![image](https://github.com/DellGEOS/AzureStackHOLs/assets/9829838/4985033c-c407-4379-9181-c66683d272fd)

**Comment by Karl-WE** [comment]
See you point, thanks for checking that. I'll close this PR.

**Comment by Karl-WE** [comment]
wrong closing
