### ISSUE TITLE
different code improvements to WAC deployment (old gateway)

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#53]
if you are interested I have different code improvements for the WAC gateway deployment including the deployment of extensions.
They might become obsolete soon due to the fundamental changes of the new WAC setup and all MS extensions come preinstalled.

let me know if you want to review it. excerpt and related idea:
https://feedback.azure.com/d365community/idea/4304fca7-fbaa-ee11-92bc-000d3a037f01

**Comment by jaromirk** [comment]
I did not see official documentation for installing new gateway. There is no MSI, there is just exe.

**Comment by Karl-WE** [comment]
exactly they have schanged from MSI to (Inno?) based installer.
I've raised in aka.ms/wacfeedback that this is fine as long we still have the ability to automate the installation.

This PR however is about the old GW.

**Comment by Karl-WE** [comment]
outdated request
