### ISSUE TITLE
Azure Stack HCI AD Precreation command changed

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#59]
added PR #58 to align with recent changes, otherwise the command will fail.

**Comment by jaromirk** [comment]
yeah, need to finish few things before I'll check the lab again and fix it for 2402

**Comment by Karl-WE** [comment]
hope my PR helps you a bit. @jaromirk

**Comment by Karl-WE** [comment]
I also hit that issue and have an open SR for that. As talked on slack. Is this issue caught? @jaromirk

**Comment by jaromirk** [comment]
I dunno. Last few deployments it worked. Did you apply windows update to system?

**Comment by Karl-WE** [comment]
No I avoided WU on the Azure Stack nodes, as per support advise as this could break things with the deployment. especially when done through sconfig. I believe updates are still part of your deployment using the API method. Docs state you may not do updates beforehand. The reason is something goes wrong with WU and PSmodules.

**Comment by jaromirk** [comment]
Iit was an issue back in 2307 or so. It was already fixed long time ago.

**Comment by Karl-WE** [comment]
This got fixed in a later update of the instruction
