### ISSUE TITLE
Scenario 23H2 preview - Task02 - Prepare Azure fails

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#66]
Connect-AzAccount fails with

PS C:\Users\Administrator.Corp>  `Connect-AzAccount -UseDeviceAuthentication`

[Login to Azure] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code [omitted] to authenticate.
`WARNING: Unable to acquire token for tenant '[omitted]' with error 'SharedTokenCacheCredential authentication
unavailable. Token acquisition failed for user services@chynet.de. Ensure that you have authenticated with a developer tool that supports Azure single sign on.'`

Workaround:
`Connect-AzAccount -UseDeviceAuthentication -Subscription '[omitted]' -Tenant ' [omitted]'`

Then executing 

`
#select subscription if more available
    $subscriptions=Get-AzSubscription
    if (($subscriptions).count -gt 1){
        $SubscriptionID=($Subscriptions | Out-GridView -OutputMode Single -Title "Please Select Subscription").ID
        $Subscriptions | Where-Object ID -eq $SubscriptionID | Select-AzSubscription
    }else{
        $SubscriptionID=$subscriptions.id
    }`

worked

Any idea why this fails? Worked some months ago. Have something changed in Azure?

**Comment by Karl-WE** [comment]
I have tried to execute this on a WS 2025 Terminal PS5.1 & WS 2022 PS 5.1
same results. It seems like the script has issues with fetching the default context for the tenant at this point

**Comment by jaromirk** [comment]
Chicken egg problem. How do you know subscription id before signing in? Warning is just a warning...

**Comment by Karl-WE** [comment]
I would not bother with a warning if it would then present me the subscriptions I have.
