### ISSUE TITLE
23H2 preview - Task 3 Step 2 fails with WinRM issue despite trusted hosts

### ISSUE THREAD

**Issue by Karl-WE** [DellGEOS/AzureStackHOLs#67]
`Invoke-Command -ComputerName $servers -ScriptBlock {
    Enable-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online -NoRestart
    Install-WindowsFeature -Name Failover-Clustering
} -Credential $Credentials`

fails to execute 
error message:

[ASNode1] Connecting to remote server ASNode1 failed with the following error message : The WinRM client cannot process the request because the
server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (ASNode1:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : ComputerNotFound,PSSessionStateBroken
[ASNode2] Connecting to remote server ASNode2 failed with the following error message : The WinRM client cannot process the request because the
server name cannot be resolved. For more information, see the about_Remote_Troubleshooting Help topic.
    + CategoryInfo          : OpenError: (ASNode2:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : ComputerNotFound,PSSessionStateBroken

![image](https://github.com/DellGEOS/AzureStackHOLs/assets/45657752/02b58f5a-5b30-446b-94ab-46fdba757d17)

Differences to previous deployments:
- Asnode1 and Asnode2 require interactive logon "user must change password at first logon"
- WinRM is configured
- WinRM trusted hosts is configured on "Management" VM

**Comment by Karl-WE** [comment]
Workaround: 
installed the features interactively but baffled by remoting does no longer work

Management VM is WS 2025 b26085

**Comment by Karl-WE** [comment]
Tried the same from a WS 2022 Management VM. Same results. Cannot remotely connect to 23H2 nodes.
Unfortunately, the 23H2 process forbids a manual domain join of the nodes, which would solve this sad comedy.

**Comment by jaromirk** [comment]
Your labconfig? I cant repro.

**Comment by Karl-WE** [comment]
Hi @jaromirk 
Thanks for your time. 

it's the same from the 23H2 AzureStackHOL

I tried to repro but it didn't happen again.
The labconfig named the VMs correctly but not their computer accounts.

**Comment by jaromirk** [comment]
Deploy log is not showing any errors?

**Comment by Karl-WE** [comment]
No there was nothing to see. Pretty wild. I guess we can close this as a rare quirk, can still ref if this happens again.
Don't want to waste your time hunting a ghost. But it happened.
