### ISSUE TITLE
vTPM

### ISSUE THREAD

**Issue by gzygadlo** [DellGEOS/AzureStackHOLs#71]
When running through this lab, I'm at the point where I deployed 2 nodes, but can't start them due to the following error

![mslaberror](https://github.com/DellGEOS/AzureStackHOLs/assets/170660878/79b9354a-1617-4593-a5e3-38c85b0a20c9)

Not sure how to get around the issue.  Unless vTPM is enabled I don't believe I can deploy Azure HCI to the lab.

**Comment by Karl-WE** [comment]
Hi @gzygadlo can you please check that UEFI /Secure Boot as well as VBS / HCVI (Core Isolation) is running correctly on your host.

You can check that msinfo32 (run as admin specifically) and Windows Security Center
Thanks for Screenshots on this.

**Comment by gzygadlo** [comment]
You can close this.  Figure I tried so many different things that in went into one of those states.

Did the following to resolve

1. Cleared TPM in BIOS of physical server
2. Re-installed the OS

**Comment by Karl-WE** [comment]
Glad to hear it is solved and it was pointing into correct direction.
HVCI relies on TPM.

As you opened the issue there should be a close button for you @gzygadlo. This would save time for maintainers to do it for you.

**Comment by Karl-WE** [comment]
#please-close
